# Generated by Django 4.2.1 on 2023-06-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Konferencija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renginys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('visitors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Konferencija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Konferencija.konferencija')),
            ],
        ),
    ]
